name: geogcdf
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - bs4=4.11.2
  - geopandas=0.13.2
  - openpyxl=3.0.10
  - pandas=1.5.1
  - pip=23.0
  - python=3.8.13
  - selenium=4.8.3
  - shapely=2.0.1
  - pip:
    - osm2geojson==0.2.4
    - overpass==0.7
    - prefect==2.10.5
    - prefect-dask==0.2.3
