#!/bin/tcsh
#PBS -N china_osm
#PBS -l nodes=5:c18a:ppn=12
#PBS -l walltime=48:00:00
#PBS -j oe

# init conda within new shell for job

# vortex [nodespec c18a or c18c for vortex-alpha, ppn up to 12 or 16 for vortex / alpha]
source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load openmpi/3.1.4/gcc-9.3.0

# hima [nodespec: hima:nogpu, ppn up to 32]
# source "/usr/local/anaconda3-4.4.0/etc/profile.d/conda.csh"
# module load anaconda3/4.4.0
# module load openmpi/3.1.4/intel-2017


unsetenv PYTHONPATH


conda activate tuff_osm

# setenv src_dir /sciclone/aiddata10/geo/master/source/geo-datasets
# setenv src_dir /sciclone/home20/smgoodman/geo-datasets
setenv src_dir /sciclone/home20/smgoodman/tuff_osm
cd ${src_dir}

setenv OMPI_MCA_rmaps_base_oversubscribe yes

# np must be set to one when using MPIPoolExecutor
# number of workers can be set in the MPIPoolExecutor(max_workers=x) call

mpirun --mca mpi_warn_on_fork 0 --map-by node -np 1 python "${src_dir}"/tuff_osm.py


